fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json }

  view:
    view_response_listener: 'force'
    formats:
      json: true