#index:
#    path: /
#    controller: App\Controller\DefaultController::index

housing:
  type     : rest
  resource : App\Controller\HousingController
  prefix   : api

user:
  type: rest
  resource: App\Controller\UserController
  prefix: api